/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Course, Assignment } from './types';

export const MOCK_COURSES: Course[] = [
  {
    id: '1',
    code: 'CPE457',
    name: 'Assembly Language and System Programming',
    difficulty: 4.7,
    workload: 4.5,
    workloadReason: 'High bulkiness (9/10).',
    lecturerTags: ['Theory-heavy', 'Detailed'],
    examStructure: 'Theory based.',
    frequency: 'Varies',
    attendance: 'Important',
    bulkiness: 9,
    examType: 'Theory',
    assignmentsInfo: 'A little difficult',
    lecturers: ['Prof S.T Apeh', 'Engr Omosigho'],
    reviews: [],
    pastQuestions: [],
  },
  {
    id: '2',
    code: 'CPE461',
    name: 'Software Engineering II',
    difficulty: 4.1,
    workload: 4.5,
    workloadReason: 'High bulkiness (9/10).',
    lecturerTags: ['Regular', 'Design-focused'],
    examStructure: 'Theory based.',
    frequency: '(E.O: regular, A.I: varies)',
    attendance: 'Required',
    bulkiness: 9,
    examType: 'Theory',
    assignmentsInfo: 'Fairly difficult',
    lecturers: ['Prof E Olaye', 'Dr Isi'],
    reviews: [],
    pastQuestions: [],
  },
  {
    id: '3',
    code: 'CPE475',
    name: 'Computer Organization and Architecture',
    difficulty: 4,
    workload: 4.25,
    workloadReason: 'Bulkiness (8.5/10).',
    lecturerTags: ['Mandatory', 'Technical'],
    examStructure: 'Theory based.',
    frequency: 'Few',
    attendance: 'Mandatory',
    bulkiness: 8.5,
    examType: 'Theory',
    assignmentsInfo: 'Difficult',
    lecturers: ['Engr Obayuwana'],
    reviews: [],
    pastQuestions: [],
  },
  {
    id: '4',
    code: 'CPE479',
    name: 'Prototyping Techniques',
    difficulty: 3.5,
    workload: 3.15,
    workloadReason: 'Bulkiness (6.3/10).',
    lecturerTags: ['Frequent', 'Engaging'],
    examStructure: 'Theory based.',
    frequency: 'Very frequent',
    attendance: 'Mandatory',
    bulkiness: 6.3,
    examType: 'Theory',
    assignmentsInfo: 'None',
    lecturers: ['Engr Sylvester', 'Engr Omosigho'],
    reviews: [],
    pastQuestions: [],
  },
  {
    id: '5',
    code: 'CPE453',
    name: 'Microprocessor Systems and Interfaces',
    difficulty: 4.3,
    workload: 4.5,
    workloadReason: 'High bulkiness (9/10).',
    lecturerTags: ['Intensive', 'Mathematical'],
    examStructure: 'Theory based.',
    frequency: 'Very',
    attendance: 'Mandatory',
    bulkiness: 9,
    examType: 'Theory',
    assignmentsInfo: 'Few & difficult',
    lecturers: ['Engr Solomon', 'Prof S.T Apeh'],
    reviews: [],
    pastQuestions: [],
  },
  {
    id: '6',
    code: 'CPE451',
    name: 'Control Theory',
    difficulty: 4,
    workload: 3.5,
    workloadReason: 'Bulkiness (7/10).',
    lecturerTags: ['Frequent', 'Architectural'],
    examStructure: 'Theory based.',
    frequency: 'Very',
    attendance: 'Required',
    bulkiness: 7,
    examType: 'Theory',
    assignmentsInfo: 'None',
    lecturers: ['Engr Sylvester'],
    reviews: [],
    pastQuestions: [],
  },
  {
    id: '7',
    code: 'CPE481',
    name: 'Numerical Computation and Statistics',
    difficulty: 4,
    workload: 3.5,
    workloadReason: 'Bulkiness (7/10).',
    lecturerTags: ['Frequent', 'Hardware-focused'],
    examStructure: 'Theory based.',
    frequency: 'Very',
    attendance: 'Mandatory',
    bulkiness: 7,
    examType: 'Theory',
    assignmentsInfo: 'Frequent',
    lecturers: ['Prof Olaye'],
    reviews: [],
    pastQuestions: [],
  },
  {
    id: '8',
    code: 'CED300',
    name: 'Entrepreneurship',
    difficulty: 3,
    workload: 3,
    workloadReason: 'Bulkiness (6/10).',
    lecturerTags: ['Practical', 'Project-based'],
    examStructure: 'Objective & Practical.',
    frequency: 'Low',
    attendance: 'Mandatory',
    bulkiness: 6,
    examType: 'Objective & Practical',
    assignmentsInfo: 'Project',
    lecturers: ['Prof S.T Apeh'],
    reviews: [],
    pastQuestions: [],
  },
  {
    id: '9',
    code: 'CPE433',
    name: 'Data Communication and Networks',
    difficulty: 4.2,
    workload: 4.0,
    workloadReason: 'Bulkiness (8/10).',
    lecturerTags: ['Technical', 'Networking'],
    examStructure: 'Theory based.',
    frequency: 'Regular',
    attendance: 'Required',
    bulkiness: 8,
    examType: 'Theory',
    assignmentsInfo: 'Lab reports',
    lecturers: ['Engr Solomon'],
    reviews: [],
    pastQuestions: [],
  },
  {
    id: '10',
    code: 'CPE401',
    name: 'Computer Laboratories',
    difficulty: 3.8,
    workload: 4.5,
    workloadReason: 'Time-consuming reports.',
    lecturerTags: ['Practical', 'Hands-on'],
    examStructure: 'Practical based.',
    frequency: 'Weekly',
    attendance: 'Mandatory',
    bulkiness: 7,
    examType: 'Practical',
    assignmentsInfo: 'Weekly reports',
    lecturers: ['Engr Omosigho', 'Engr Sylvester'],
    reviews: [],
    pastQuestions: [],
  },
];

export const MOCK_ASSIGNMENTS: Assignment[] = [
  { id: 'a1', courseId: '1', title: 'Lab 5: Recursion', deadline: '2026-04-05', status: 'In Progress', priority: 'Medium', reminders: true },
  { id: 'a2', courseId: '2', title: 'Problem Set 8: Series', deadline: '2026-04-02', status: 'Not Started', priority: 'High', reminders: true },
  { id: 'a3', courseId: '1', title: 'Final Project Proposal', deadline: '2026-04-10', status: 'Done', priority: 'Low', reminders: false },
];
